// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterByID = `-- name: GetCharacterByID :one
SELECT id, slug, name, blurb, avatar_url, base_prompt, bot_username, is_active, position, created_at, updated_at FROM characters WHERE id = $1
`

func (q *Queries) GetCharacterByID(ctx context.Context, id pgtype.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByID, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Blurb,
		&i.AvatarUrl,
		&i.BasePrompt,
		&i.BotUsername,
		&i.IsActive,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCharacters = `-- name: ListActiveCharacters :many
SELECT id, slug, name, blurb, avatar_url, base_prompt, bot_username, is_active, position, created_at, updated_at FROM characters
WHERE is_active = TRUE
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListActiveCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listActiveCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Blurb,
			&i.AvatarUrl,
			&i.BasePrompt,
			&i.BotUsername,
			&i.IsActive,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
