// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_flow.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assistantReplyExistsAfter = `-- name: AssistantReplyExistsAfter :one
SELECT EXISTS(
    SELECT 1 FROM tg_messages
    WHERE chat_id = $1 AND role = 'assistant' AND created_at > $2
) AS reply_exists
`

type AssistantReplyExistsAfterParams struct {
	ChatID    pgtype.UUID        `json:"chat_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AssistantReplyExistsAfter(ctx context.Context, arg AssistantReplyExistsAfterParams) (bool, error) {
	row := q.db.QueryRow(ctx, assistantReplyExistsAfter, arg.ChatID, arg.CreatedAt)
	var reply_exists bool
	err := row.Scan(&reply_exists)
	return reply_exists, err
}

const getCharacterByID = `-- name: GetCharacterByID :one
SELECT id, slug, base_prompt FROM characters WHERE id = $1
`

type GetCharacterByIDRow struct {
	ID         pgtype.UUID `json:"id"`
	Slug       string      `json:"slug"`
	BasePrompt string      `json:"base_prompt"`
}

func (q *Queries) GetCharacterByID(ctx context.Context, id pgtype.UUID) (GetCharacterByIDRow, error) {
	row := q.db.QueryRow(ctx, getCharacterByID, id)
	var i GetCharacterByIDRow
	err := row.Scan(&i.ID, &i.Slug, &i.BasePrompt)
	return i, err
}

const getDefaultContextWithModelForCharacter = `-- name: GetDefaultContextWithModelForCharacter :one
SELECT
    ctx.id          AS context_id,
    ctx.slug        AS context_slug,
    ctx.name        AS context_name,
    ctx.prompt      AS context_prompt,
    ctx.is_age_restricted,
    mc.id           AS model_config_id,
    mc.slug         AS model_slug,
    mc.model        AS model_name,
    mc.temperature,
    mc.top_p,
    mc.max_tokens
FROM contexts ctx
JOIN model_configs mc ON mc.id = ctx.model_config_id
WHERE ctx.character_id = $1 AND ctx.is_active = TRUE
ORDER BY ctx.position ASC, ctx.created_at ASC
LIMIT 1
`

type GetDefaultContextWithModelForCharacterRow struct {
	ContextID       pgtype.UUID   `json:"context_id"`
	ContextSlug     string        `json:"context_slug"`
	ContextName     string        `json:"context_name"`
	ContextPrompt   string        `json:"context_prompt"`
	IsAgeRestricted bool          `json:"is_age_restricted"`
	ModelConfigID   pgtype.UUID   `json:"model_config_id"`
	ModelSlug       string        `json:"model_slug"`
	ModelName       string        `json:"model_name"`
	Temperature     pgtype.Float8 `json:"temperature"`
	TopP            pgtype.Float8 `json:"top_p"`
	MaxTokens       pgtype.Int4   `json:"max_tokens"`
}

func (q *Queries) GetDefaultContextWithModelForCharacter(ctx context.Context, characterID pgtype.UUID) (GetDefaultContextWithModelForCharacterRow, error) {
	row := q.db.QueryRow(ctx, getDefaultContextWithModelForCharacter, characterID)
	var i GetDefaultContextWithModelForCharacterRow
	err := row.Scan(
		&i.ContextID,
		&i.ContextSlug,
		&i.ContextName,
		&i.ContextPrompt,
		&i.IsAgeRestricted,
		&i.ModelConfigID,
		&i.ModelSlug,
		&i.ModelName,
		&i.Temperature,
		&i.TopP,
		&i.MaxTokens,
	)
	return i, err
}

const getMostRecentChatJoinedForUserCharacter = `-- name: GetMostRecentChatJoinedForUserCharacter :one
SELECT
    c.id            AS chat_id,
    c.status        AS chat_status,
    c.summary       AS chat_summary,
    c.updated_at    AS chat_updated_at,
    ctx.id          AS context_id,
    ctx.slug        AS context_slug,
    ctx.name        AS context_name,
    ctx.prompt      AS context_prompt,
    ctx.is_age_restricted,
    ch.id           AS character_id,
    ch.slug         AS character_slug,
    ch.name         AS character_name,
    ch.base_prompt  AS character_base_prompt,
    mc.id           AS model_config_id,
    mc.slug         AS model_slug,
    mc.model        AS model_name,
    mc.temperature,
    mc.top_p,
    mc.max_tokens
FROM chats c
JOIN contexts ctx ON ctx.id = c.context_id
JOIN characters ch ON ch.id = ctx.character_id
JOIN model_configs mc ON mc.id = ctx.model_config_id
WHERE c.user_id = $1 AND ch.id = $2
ORDER BY c.updated_at DESC
LIMIT 1
`

type GetMostRecentChatJoinedForUserCharacterParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetMostRecentChatJoinedForUserCharacterRow struct {
	ChatID              pgtype.UUID        `json:"chat_id"`
	ChatStatus          string             `json:"chat_status"`
	ChatSummary         pgtype.Text        `json:"chat_summary"`
	ChatUpdatedAt       pgtype.Timestamptz `json:"chat_updated_at"`
	ContextID           pgtype.UUID        `json:"context_id"`
	ContextSlug         string             `json:"context_slug"`
	ContextName         string             `json:"context_name"`
	ContextPrompt       string             `json:"context_prompt"`
	IsAgeRestricted     bool               `json:"is_age_restricted"`
	CharacterID         pgtype.UUID        `json:"character_id"`
	CharacterSlug       string             `json:"character_slug"`
	CharacterName       string             `json:"character_name"`
	CharacterBasePrompt string             `json:"character_base_prompt"`
	ModelConfigID       pgtype.UUID        `json:"model_config_id"`
	ModelSlug           string             `json:"model_slug"`
	ModelName           string             `json:"model_name"`
	Temperature         pgtype.Float8      `json:"temperature"`
	TopP                pgtype.Float8      `json:"top_p"`
	MaxTokens           pgtype.Int4        `json:"max_tokens"`
}

func (q *Queries) GetMostRecentChatJoinedForUserCharacter(ctx context.Context, arg GetMostRecentChatJoinedForUserCharacterParams) (GetMostRecentChatJoinedForUserCharacterRow, error) {
	row := q.db.QueryRow(ctx, getMostRecentChatJoinedForUserCharacter, arg.UserID, arg.ID)
	var i GetMostRecentChatJoinedForUserCharacterRow
	err := row.Scan(
		&i.ChatID,
		&i.ChatStatus,
		&i.ChatSummary,
		&i.ChatUpdatedAt,
		&i.ContextID,
		&i.ContextSlug,
		&i.ContextName,
		&i.ContextPrompt,
		&i.IsAgeRestricted,
		&i.CharacterID,
		&i.CharacterSlug,
		&i.CharacterName,
		&i.CharacterBasePrompt,
		&i.ModelConfigID,
		&i.ModelSlug,
		&i.ModelName,
		&i.Temperature,
		&i.TopP,
		&i.MaxTokens,
	)
	return i, err
}

const getUserMessageByTelegramID = `-- name: GetUserMessageByTelegramID :one
SELECT id, created_at
FROM tg_messages
WHERE chat_id = $1 AND telegram_message_id = $2 AND role = 'user'
`

type GetUserMessageByTelegramIDParams struct {
	ChatID            pgtype.UUID `json:"chat_id"`
	TelegramMessageID pgtype.Int8 `json:"telegram_message_id"`
}

type GetUserMessageByTelegramIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserMessageByTelegramID(ctx context.Context, arg GetUserMessageByTelegramIDParams) (GetUserMessageByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getUserMessageByTelegramID, arg.ChatID, arg.TelegramMessageID)
	var i GetUserMessageByTelegramIDRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertAssistantMessage = `-- name: InsertAssistantMessage :exec
INSERT INTO tg_messages
    (chat_id, role, content, telegram_message_id, llm_model, llm_tokens_in, llm_tokens_out)
VALUES ($1, 'assistant', $2, $3, $4, $5, $6)
`

type InsertAssistantMessageParams struct {
	ChatID            pgtype.UUID `json:"chat_id"`
	Content           string      `json:"content"`
	TelegramMessageID pgtype.Int8 `json:"telegram_message_id"`
	LlmModel          pgtype.Text `json:"llm_model"`
	LlmTokensIn       pgtype.Int4 `json:"llm_tokens_in"`
	LlmTokensOut      pgtype.Int4 `json:"llm_tokens_out"`
}

func (q *Queries) InsertAssistantMessage(ctx context.Context, arg InsertAssistantMessageParams) error {
	_, err := q.db.Exec(ctx, insertAssistantMessage,
		arg.ChatID,
		arg.Content,
		arg.TelegramMessageID,
		arg.LlmModel,
		arg.LlmTokensIn,
		arg.LlmTokensOut,
	)
	return err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO chats (user_id, context_id)
VALUES ($1, $2)
RETURNING id, status, summary, updated_at
`

type InsertChatParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ContextID pgtype.UUID `json:"context_id"`
}

type InsertChatRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	Summary   pgtype.Text        `json:"summary"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (InsertChatRow, error) {
	row := q.db.QueryRow(ctx, insertChat, arg.UserID, arg.ContextID)
	var i InsertChatRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Summary,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserMessageIdempotent = `-- name: InsertUserMessageIdempotent :one
INSERT INTO tg_messages (chat_id, role, content, telegram_message_id)
VALUES ($1, 'user', $2, $3)
ON CONFLICT (chat_id, telegram_message_id)
    WHERE telegram_message_id IS NOT NULL
DO NOTHING
RETURNING id, created_at
`

type InsertUserMessageIdempotentParams struct {
	ChatID            pgtype.UUID `json:"chat_id"`
	Content           string      `json:"content"`
	TelegramMessageID pgtype.Int8 `json:"telegram_message_id"`
}

type InsertUserMessageIdempotentRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertUserMessageIdempotent(ctx context.Context, arg InsertUserMessageIdempotentParams) (InsertUserMessageIdempotentRow, error) {
	row := q.db.QueryRow(ctx, insertUserMessageIdempotent, arg.ChatID, arg.Content, arg.TelegramMessageID)
	var i InsertUserMessageIdempotentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT role, content, created_at
FROM tg_messages
WHERE chat_id = $1
  AND role IN ('user', 'assistant')
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	Limit  int32       `json:"limit"`
}

type ListRecentMessagesRow struct {
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMessagesRow
	for rows.Next() {
		var i ListRecentMessagesRow
		if err := rows.Scan(&i.Role, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChatUpdatedAt = `-- name: TouchChatUpdatedAt :exec
UPDATE chats SET updated_at = NOW() WHERE id = $1
`

func (q *Queries) TouchChatUpdatedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchChatUpdatedAt, id)
	return err
}
