// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TelegramID   int64              `json:"telegram_id"`
	Username     pgtype.Text        `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	LanguageCode pgtype.Text        `json:"language_code"`
	IsPremium    bool               `json:"is_premium"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
