// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	UpsertUserFromTelegram(ctx context.Context, arg UpsertUserFromTelegramParams) (User, error)
}

var _ Querier = (*Queries)(nil)
