// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, username, first_name, last_name, language_code, is_premium, created_at, updated_at, active_chat_id, is_adult, age_verified_at FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LanguageCode,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveChatID,
		&i.IsAdult,
		&i.AgeVerifiedAt,
	)
	return i, err
}

const upsertUserFromTelegram = `-- name: UpsertUserFromTelegram :one
INSERT INTO users (telegram_id, username, first_name, last_name, language_code, is_premium)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (telegram_id) DO UPDATE SET
    username      = EXCLUDED.username,
    first_name    = EXCLUDED.first_name,
    last_name     = EXCLUDED.last_name,
    language_code = EXCLUDED.language_code,
    is_premium    = EXCLUDED.is_premium,
    updated_at    = NOW()
RETURNING id, telegram_id, username, first_name, last_name, language_code, is_premium, created_at, updated_at, active_chat_id, is_adult, age_verified_at
`

type UpsertUserFromTelegramParams struct {
	TelegramID   int64       `json:"telegram_id"`
	Username     pgtype.Text `json:"username"`
	FirstName    string      `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	LanguageCode pgtype.Text `json:"language_code"`
	IsPremium    bool        `json:"is_premium"`
}

func (q *Queries) UpsertUserFromTelegram(ctx context.Context, arg UpsertUserFromTelegramParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromTelegram,
		arg.TelegramID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.LanguageCode,
		arg.IsPremium,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LanguageCode,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveChatID,
		&i.IsAdult,
		&i.AgeVerifiedAt,
	)
	return i, err
}
